name: Nuitka Multiplatform Build

on:
  push:
    tags:
      - 'v*'   # spustí sa keď vytvoríš tag, napr. v0.1, v1.0.0
  workflow_dispatch: # môžeš spustiť aj manuálne

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install nuitka

      - name: Run compile script
        run: python compile.py

      - name: Package build
        run: |
          zip -r build-${{ runner.os }}.zip build_output/*

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: ModuleLoader-${{ runner.os }}
          path: build-${{ runner.os }}.zip

  release:
    name: Create GitHub Release
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v3
        with:
          path: ./artifacts

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: ./artifacts/**/*.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
